const ACTIONS = {
  LOGIN: "LOGIN",
  GET_TOKEN: "GET_TOKEN",
  GET_USER: "GET_USER",
  LOGOUT: "LOGOUT",
  GET_POSTS_SUCCESS: "GET_POSTS_SUCCESS",
  GET_POSTS_FAILURE: "GET_POSTS_FAILURE",
  GET_POSTS_REQUEST: "GET_POSTS_REQUEST",
  NOTIFY: "NOTIFY",
  UNNOTIFY: "UNNOTIFY",
  TOKEN_ADD: 'TOKEN_ADD'
};

export default ACTIONS;
